#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
#alias ls='ls --color=auto'
#alias l='ls --color=auto'
#alias ll='ls --color=auto -lh'
#alias cd='zoxide'
alias ls='exa'
alias l='exa'
alias ll='exa -lh'
alias la='exa -a'
alias lla='exa -a -lh'
alias grep='grep --color=auto'
alias wsesdown='waydroid session stop'
alias wsesup='waydroid session start'
alias wfull='waydroid show-full-ui'
alias wcondown='sudo waydroid container stop'
alias wconup='sudo waydroid container start'
alias wconres='sudo waydroid container restart'
alias wsysdown='sudo systemctl stop waydroid-container.service'
alias wsysup='sudo systemctl start waydroid-container.service'
alias wsysres='sudo systemctl restart waydroid-container.service'
alias wappsrm='sudo rm -rf ~/.local/share/applications/*aydroid*'
alias winitex='sudo waydroid init -f'
alias winit='sudo waydroid init'
alias winitg='sudo waydroid init -s GAPPS'
alias wshell='sudo waydroid shell'
alias hypedit='nvim ~/.config/hypr/hyprland.conf'
alias hypnedit='nano ~/.config/hypr/hyprland.conf'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias pu='paru -Syu'
alias puy='paru --noconfirm -Syu'
alias pi='paru -S'
alias pin='paru --needed -S'
alias piy='paru --noconfirm -S'
alias piny='paru --needed --noconfirm -S'
alias pr='paru -R'
alias pss='paru -Ss'
alias cl='cd && clear'
alias shadow='exec ~/apps/ShadowPC.AppImage'
alias net-scan='sudo nmap -sn 192.168.0.0/24'
alias c='clear'
alias yu='yay -Syu'
alias fu='flatpak update'
alias waydroid-size-tablet='waydroid prop set persist.waydroid.width 1200 && waydroid prop set persist.waydroid.height 900'
alias waydroid-size-hybrid='waydroid prop set persist.waydroid.width 800 && waydroid prop set persist.waydroid.height 900'
alias waydroid-size-phone='waydroid prop set persist.waydroid.width 600 && waydroid prop set persist.waydroid.height 900'
alias waydroid-size='waydroid prop set persist.waydroid.width "" && waydroid prop set persist.waydroid.height ""'
alias swbg='bash /home/matysek/scripts/swaybg-secret.sh'
alias rb='sudo reboot'
alias eb='exec bash'
alias nb='nvim /home/matysek/.bashrc'
alias sysstop='sudo systemctl stop'
alias sysstart='sudo systemctl start'
alias sysdisable='sudo systemctl disable'
alias sysenable='sudo systemctl enable'
alias waydroid_script='sudo /home/matysek/Github/waydroid_script/venv/bin/python3 /home/matysek/Github/waydroid_script/main.py'
alias waydroid_multi_off='waydroid prop set persist.waydroid.multi_windows false'
alias waydroid_multi_on='waydroid prop set persist.waydroid.multi_windows true'
alias wget='wget2 --progress bar'
alias bios='sudo systemctl reboot --firmware-setup'
alias buds_on='bluetoothctl connect 80:9F:F5:9F:1F:DE'
alias buds_off='bluetoothctl disconnect 80:9F:F5:9F:1F:DE'
alias vpncz='nordvpn connect Czech_Republic'
alias update-posh='curl -s https://ohmyposh.dev/install.sh | sudo bash -s'
alias nvimsudo='sudo EDITOR=nvim visudo'
alias nvimsudome='sudo EDITOR=nvim visudo /etc/sudoers.d/00_matysek'
alias olivia='ollama run olivia:latest'
alias evelyn='ollama run evelyn:latest'
alias ex='exit'
alias cd='z'
alias ai-vm='ssh -i ~/.ssh/UbuntuAMDKey.pem matysek@4.185.31.18'
alias wifi='nmcli device wifi connect dvoracek5.ernet'
alias n='nvim'
alias paper='ssh -i ~/.ssh/paper paperspace@74.82.28.125'
alias ff='fastfetch'

PS1='[\u@\h \W]\$ '

# OhMyPosh
eval "$(oh-my-posh init bash --config /home/$USER/posh/catppuccin_mocha.omp.json)"
eval "$(zoxide init bash)"

export OLLAMA_HOST=http://74.82.29.131:11434
export EDITOR=nvim
