#!/bin/bash
echo "Updating system!"
sudo pacman -Syyu

ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
    echo -e "yay was located, moving on.\n"
    yay -Suy
else
    echo -e "Installing yay"
    sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si
    yay -Y --gendb
    yay -Syu --devel
    yay -Y --devel --save
    yay -Syu
    cd ..
fi

echo "Installing chaotic-aur"
sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key 3056513887B78AEB
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
sudo chown $USER /etc/pacman.conf
sleep 0.2
sudo echo "
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf
sudo chown root /etc/pacman.conf
sleep 0.2
sudo pacman -Syu

echo "Adding archlinuxcn"
sudo chown $USER /etc/pacman.conf
sleep 0.2
sudo echo '
[archlinuxcn]
Server = https://repo.archlinuxcn.org/$arch' >>/etc/pacman.conf
sudo chown root /etc/pacman.conf
sleep 0.2
sudo pacman-key --lsign-key "farseerfc@archlinux.org"
sudo pacman -S archlinuxcn-keyring
sudo pacman -Syyu

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    sudo pacman -S --needed hyprland-git kitty waybar \
        swaybg swaylock-effects wofi wlogout mako nautilus \
        ttf-jetbrains-mono-nerd noto-fonts-emoji \
        polkit-gnome python-requests starship \
        swappy grim slurp pamixer brightnessctl gvfs \
        bluez bluez-utils lxappearance xfce4-settings \
        dracula-gtk-theme dracula-icons-git xdg-desktop-portal-hyprland \
        brave-bin bash-completion neofetch wget flatpak gnome-software waydroid \
        gnome-calculator code hyprpicker scrcpy vlc grub-customizer \
        linux-xanmod-anbox linux-xanmod-anbox-headers qt6ct nwg-look wget2

    flatpak install flathub com.simplenote.Simplenote

    # Start the bluetooth service
    echo -e "Starting the Bluetooth Service...\n"
    sudo systemctl enable --now bluetooth.service
    sleep 2

fi

read -n1 -rep 'Would you like to setup gdm login screnn? (y,n)' GDMSV
if [[ $GDMSV == "Y" || $GDMSV == "y" ]]; then
    sudo pacman -S --needed gdm
    echo "Starting gdm service"
    sudo systemctl enable --now gdm.service
    sleep 2

fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    cp -r hypr ~/.config/
    cp -r kitty ~/.config/
    cp -r mako ~/.config/
    cp -r waybar ~/.config/
    cp -r swaylock ~/.config/
    cp -r wofi ~/.config/
    cp -r wlogout ~/.config/
    if [ -d ~/Pictures ]; then
        echo "Pictures folder exists"
    else
        mkdir ~/Pictures
    fi
    wget https://mistrmochov.blob.core.windows.net/set-hypr/pics.tar.gz
    tar -xf pics.tar.gz
    mv hihi ~/Pictures/
    mv Wallpapers ~/Pictures/
    wget https://mistrmochov.blob.core.windows.net/set-hypr/swaybgscr.tar.gz
    tar -xf swaybgscr.tar.gz
    if [ -d ~/scripts ]; then
        echo "Scripts folder exists, skipping!"
    else
        mkdir ~/scripts
    fi
    mv swaybgscr ~/scripts/
    chmod +x ~/scripts/swaybgscr/hyprcheck.sh
    chmod +x ~/scripts/swaybgscr/swaybgscr.sh
fi

### Install teh starship shell ###
read -n1 -rep 'Would you like to install the starship shell? (y,n)' STAR
if [[ $STAR == "Y" || $STAR == "y" ]]; then
    # install the starship shell
    echo -e "Updating .bashrc...\n"
    echo -e '\neval "$(starship init bash)"' >>~/.bashrc
    echo -e "copying starship config file to ~/.confg ...\n"
    cp starship.toml ~/.config/
fi

read -n1 -rep 'Would you like to install oh-my-posh? (y,n)' POSH
if [[ $POSH == "Y" || $POSH == "y" ]]; then
    # install oh-my-posh
    curl -s https://ohmyposh.dev/install.sh | sudo bash -s
    if [ -d ~/posh ]; then
        echo "Posh dir exists, skipping!"
    else
        mkdir ~/posh
    fi
    wget https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/catppuccin_mocha.omp.json
    mv catppuccin_mocha.omp.json ~/posh/
    echo '
# OhMyPosh
eval "$(oh-my-posh init bash --config /home/$USER/posh/catppuccin_mocha.omp.json)"' >>~/.bashrc
fi

read -n1 -rep 'Would you like to restore my .bashrc file? (y,n)' BASHRC
if [[ $BASHRC =="Y" || $BASHRC == "y" ]]; then
mv ~/.bashrc ~/.bashrc.bak
mv bashrc ~/.bashrc
fi

echo -e "Script had completed.\n"
read -n1 -rep 'Would you like to reboot now? (y,n)' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    sudo reboot
else
    exit
fi
